server:
    port: 8443
    servlet:
      session:
        timeout: 30
    ssl:
      key-store: letsencrypt.jks
      key-store-password: hhhhhh
      key-password: hhhhhh

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://errorstack.cvivhkze1ato.us-east-2.rds.amazonaws.com:3306/db1?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: hhhhhhhh
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true