spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://18.188.1.175:3306/db1?serverTimezone=UTC&characterEncoding=UTF-8
    username: spring
    password: hhhh
  jpa:
    database: MYSQL