server:
  port: 8443
  servlet:
    session:
      timeout: 30
    ssl:
      enabled: true
      key-aliasa: kimstore
      key-store: kimstore.jks
      key-store-password: 'hhhhhh'
      key-password: 'hhhhhh'
      trust-store: kimtrust.pkcs12
      trust-store-password: 'hhhhhh'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://18.188.1.175:3306/db1?serverTimezone=UTC&characterEncoding=UTF-8
    username: spring
    password: hhhh
  jpa:
    database: MYSQL